resources:
  - ux_backend_sa.yaml
  - ux_backend_role.yaml
  - ux_backend_role_binding.yaml
  - oauth_proxy_role.yaml
  - oauth_proxy_role_binding.yaml
  - devicefinder_sa.yaml
  - devicefinder-role.yaml
  - devicefinder-role-binding.yaml
  - devicefinder-cluster-role.yaml
  - devicefinder-cluster-role-binding.yaml
