apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  creationTimestamp: null
  name: cephfilesystemsubvolumegroups.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephFilesystemSubVolumeGroup
    listKind: CephFilesystemSubVolumeGroupList
    plural: cephfilesystemsubvolumegroups
    singular: cephfilesystemsubvolumegroup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - description: Name of the CephFileSystem
      jsonPath: .spec.filesystemName
      name: Filesystem
      type: string
    - jsonPath: .spec.quota
      name: Quota
      type: string
    - jsonPath: .status.info.pinning
      name: Pinning
      priority: 1
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              dataPoolName:
                type: string
              filesystemName:
                type: string
                x-kubernetes-validations:
                - message: filesystemName is immutable
                  rule: self == oldSelf
              name:
                type: string
                x-kubernetes-validations:
                - message: name is immutable
                  rule: self == oldSelf
              pinning:
                properties:
                  distributed:
                    maximum: 1
                    minimum: 0
                    nullable: true
                    type: integer
                  export:
                    maximum: 256
                    minimum: -1
                    nullable: true
                    type: integer
                  random:
                    maximum: 1
                    minimum: 0
                    nullable: true
                    type: number
                type: object
                x-kubernetes-validations:
                - message: only one pinning type should be set
                  rule: (has(self.export) && !has(self.distributed) && !has(self.random))
                    || (!has(self.export) && has(self.distributed) && !has(self.random))
                    || (!has(self.export) && !has(self.distributed) && has(self.random))
                    || (!has(self.export) && !has(self.distributed) && !has(self.random))
              quota:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
            required:
            - filesystemName
            type: object
          status:
            properties:
              info:
                additionalProperties:
                  type: string
                nullable: true
                type: object
              observedGeneration:
                format: int64
                type: integer
              phase:
                type: string
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
