apiVersion: v1
data:
  CSIADDONS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  CSIADDONS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  CSIADDONS_SUBSCRIPTION_CHANNEL: alpha
  CSIADDONS_SUBSCRIPTION_NAME: csi-addons
  CSIADDONS_SUBSCRIPTION_PACKAGE: csi-addons
  CSIADDONS_SUBSCRIPTION_STARTINGCSV: csi-addons.v0.7.0
  IBM_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  IBM_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  IBM_SUBSCRIPTION_CHANNEL: stable-v1.4
  IBM_SUBSCRIPTION_NAME: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_PACKAGE: ibm-storage-odf-operator
  IBM_SUBSCRIPTION_STARTINGCSV: ibm-storage-odf-operator.v1.4.1
  NOOBAA_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  NOOBAA_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  NOOBAA_SUBSCRIPTION_CHANNEL: alpha
  NOOBAA_SUBSCRIPTION_NAME: noobaa-operator
  NOOBAA_SUBSCRIPTION_PACKAGE: noobaa-operator
  NOOBAA_SUBSCRIPTION_STARTINGCSV: noobaa-operator.v5.14.0
  OCS_SUBSCRIPTION_CATALOGSOURCE: odf-catalogsource
  OCS_SUBSCRIPTION_CATALOGSOURCE_NAMESPACE: openshift-marketplace
  OCS_SUBSCRIPTION_CHANNEL: alpha
  OCS_SUBSCRIPTION_NAME: ocs-operator
  OCS_SUBSCRIPTION_PACKAGE: ocs-operator
  OCS_SUBSCRIPTION_STARTINGCSV: ocs-operator.v4.14.0
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: true
      resourceName: 4fd470de.openshift.io
kind: ConfigMap
metadata:
  name: odf-operator-manager-config
