apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: oauth-proxy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oauth-proxy-role
subjects:
- kind: ServiceAccount
  name: ux-backend-server
  namespace: openshift-storage
