apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ocs-devicefinder-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocs-devicefinder-role
subjects:
- kind: ServiceAccount
  name: ocs-devicefinder-sa
  namespace: openshift-storage
