apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ux-backend-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ux-backend-server
subjects:
- kind: ServiceAccount
  name: ux-backend-server
  namespace: openshift-storage
