resources:
- csv.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.22"}]'
  olm.skipRange: ""
patches:
- patch: '[{"op": "replace", "path": "/spec/replaces", "value": ""}]'
  target:
    kind: ClusterServiceVersion
    name: cnsa-dependencies.v0.0.0
