apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- odf-operator.clusterserviceversion.yaml
patchesStrategicMerge:
- odf-operator.csv.icon.yaml
- odf-operator.csv.card-description.yaml
commonAnnotations:
  olm.properties: '[{"type": "olm.maxOpenShiftVersion", "value": "4.17"}]'
  olm.skipRange: ""
  operators.operatorframework.io/operator-type: standalone
patches:
- patch: '[{"op": "replace", "path": "/spec/replaces", "value": ""}]'
  target:
    kind: ClusterServiceVersion
    name: odf-operator.v0.0.0
