---
name: image-builder

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build operator docker image
      run: make docker-build

  bundle-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build operator bundle docker image
      run: make bundle-build

  catalog-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build catalog docker image
      env:
        IMAGE_REGISTRY: localhost:5000
        OPM_RENDER_OPTS: --use-http
      run: |
        docker run -d -p 5000:5000 --name registry registry:2
        make bundle-build bundle-push catalog-build
