name: image-publisher

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: ocs-dev
      IMAGE_TAG:
        required: false
        default: ""

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push docker images
      env:
        REGISTRY_NAMESPACE: ${{ github.event.inputs.REGISTRY_NAMESPACE }}
        IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
        IMAGE_TAG_SHA: ${{ github.ref_name }}-${{ github.sha }}
      run: |
        # Set IMAGE_TAG to a calculated <branch>-<sha> if not specified
        export IMAGE_TAG=${IMAGE_TAG:-${IMAGE_TAG_SHA:0:-33}}
        make docker-build docker-push
        make bundle-build bundle-push
        make catalog-build catalog-push
        make catalog-deps-build catalog-deps-push
