---
name: image-builder

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.20"]
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build operator docker image
      run: make docker-build

  bundle-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.20"]
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build operator bundle docker image
      run: |
        make bundle-build
        msg='Uncommitted bundle changes. run `make bundle` and commit results.'
        # We are using `--ignore-matching-lines` flag with the pattern `createdAt`
        # to exclude lines with the timestamp from being considered, as the CSV file
        # consistently receives a new timestamp during generation with operator-sdk 1.26 onwards.
        git diff --exit-code --ignore-matching-lines createdAt bundle || (echo -e '\e[31m'"$msg"; exit 1)

  catalog-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.20"]
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build catalog docker image
      env:
        IMAGE_REGISTRY: localhost:5000
        OPM_RENDER_OPTS: --use-http
      run: |
        docker run -d -p 5000:5000 --name registry registry:2
        make bundle-build bundle-push catalog-build catalog-deps-build
        msg='Uncommitted catalog changes. run `make catalog` and commit results.'
        git diff --exit-code catalog || (echo -e '\e[31m'"$msg"; exit 1)
